# Generated by Django 4.2.16 on 2024-10-29 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_notification_task_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
