# Generated by Django 4.2.16 on 2024-10-29 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelatedModel',
        ),
    ]
