# Generated by Django 4.2.16 on 2024-10-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_delete_relatedmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='task_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
